sudo: true
dist: trusty

language: node_js

node_js:
  - "4"
  - "6"
  - "10"

services:
  - postgresql

addons:
  - "9.6"

script:
  - npm run test-pgsql

before_script:
  - psql -c "CREATE DATABASE seq_db;" -U postgres